
{{ config (
  materialized= 'view',
  schema= 'QUICKBOOKS',
  tags= ["staging", "daily"]
)
}}

WITH PURCHASE AS (
    SELECT *
    FROM {{ref('V_PURCHASE_HEADER_STG')}}
),

PURCHASE_LINES AS (
    SELECT *
    FROM {{ref('V_PURCHASE_LINE_STG')}}
),
ITEMS AS (
    SELECT *
    FROM {{ref('W_ITEMS_D')}}
),
FINAL AS (
    SELECT
        --DLHK
        PURCHASE_LINES.K_PURCHASE_LINE_DLHK
        ,PURCHASE.K_PURCHASE_DLHK
        ,PURCHASE.K_ACCOUNT_DLHK AS K_PURCHASE_ACCOUNT_DLHK
        ,PURCHASE.K_CURRENCY_DLHK AS K_PURCHASE_CURRENCY_DLHK
        ,PURCHASE.K_CUSTOMER_DLHK AS K_PURCHASE_CUSTOMER_DLHK
        ,PURCHASE.K_EMPLOYEE_DLHK     
        ,PURCHASE.K_VENDOR_DLHK
        ,PURCHASE_LINES.K_ACCOUNT_EXPENSE_DLHK
        ,PURCHASE_LINES.K_ITEM_EXPENSE_CUSTOMER_DLHK
        ,PURCHASE_LINES.K_ACCOUNT_EXPENSE_CUSTOMER_DLHK
        ,PURCHASE_LINES.K_ITEM_EXPENSE_DLHK
        ,PURCHASE_LINES.K_ITEM_EXPENSE_ACCOUNT_DLHK        
        ,COALESCE(PURCHASE_LINES.K_ACCOUNT_EXPENSE_DLHK,PURCHASE_LINES.K_ITEM_EXPENSE_ACCOUNT_DLHK) AS K_ACCOUNT_DLHK
        ,COALESCE(PURCHASE_LINES.K_ACCOUNT_EXPENSE_CUSTOMER_DLHK,PURCHASE_LINES.K_ITEM_EXPENSE_CUSTOMER_DLHK) AS K_CUSTOMER_DLHK
        --BK 
        ,PURCHASE.K_PURCHASE_BK
        ,PURCHASE.K_CURRENCY_BK
        ,PURCHASE.K_ACCOUNT_BK AS K_PURCHASE_ACCOUNT_BK
        ,PURCHASE.K_DEPARTMENT_BK
        ,PURCHASE.K_PAYMENT_METHOD_BK
        ,PURCHASE.K_CUSTOMER_BK AS K_PURCHASE_CUSTOMER_BK
        ,PURCHASE.K_VENDOR_BK
        ,PURCHASE.K_EMPLOYEE_BK
        ,PURCHASE.K_TAX_CODE_BK AS K_PURCHASE_TAX_CODE_BK
        ,PURCHASE_LINES.K_ITEM_EXPENSE_ACCOUNT_BK
        ,PURCHASE_LINES.K_ACCOUNT_EXPENSE_ACCOUNT_BK
        ,PURCHASE_LINES.K_ACCOUNT_EXPENSE_CLASS_BK
        ,PURCHASE_LINES.K_ACCOUNT_EXPENSE_CUSTOMER_BK
        ,PURCHASE_LINES.K_ACCOUNT_EXPENSE_TAX_CODE_BK
        ,PURCHASE_LINES.K_ITEM_EXPENSE_CLASS_BK
        ,PURCHASE_LINES.K_ITEM_EXPENSE_CUSTOMER_BK
        ,PURCHASE_LINES.K_ITEM_EXPENSE_ITEM_BK
        ,PURCHASE_LINES.K_ITEM_EXPENSE_TAX_CODE_BK

        ,COALESCE(PURCHASE_LINES.K_ACCOUNT_EXPENSE_ACCOUNT_BK,PURCHASE_LINES.K_ITEM_EXPENSE_ACCOUNT_BK) AS K_ACCOUNT_BK
        ,COALESCE(PURCHASE_LINES.K_ACCOUNT_EXPENSE_CUSTOMER_BK,PURCHASE_LINES.K_ITEM_EXPENSE_CUSTOMER_BK) AS K_CUSTOMER_BK
        
        --ATTRIBUTES
        ,PURCHASE_LINES.A_INDEX AS A_PURCHASE_LINE_INDEX
        ,COALESCE(PURCHASE_LINES.A_ACCOUNT_EXPENSE_BILLABLE_STATUS,PURCHASE_LINES.A_ITEM_EXPENSE_BILLABLE_STATUS) AS A_BILLABLE_STATUS        
        ,coalesce(PURCHASE_LINES.A_DESCRIPTION, ITEMS.A_ITEM_NAME) as A_DESCRIPTION       
                
        ,PURCHASE.A_PAYMENT_TYPE
        ,PURCHASE.A_PRINT_STATUS
        ,PURCHASE.A_GLOBAL_TAX_CALCULATION
        ,PURCHASE.A_CREATED_AT_DTS AS A_PURCHASE_CREATED_AT_DTS
        ,PURCHASE.A_UPDATED_AT_DTS AS A_PURCHASE_UPDATED_AT_DTS        
        ,PURCHASE.A_TRANSACTION_DATE AS A_PURCHASE_TRANSACTION_DATE
        ,PURCHASE.A_TRANSACTION_SOURCE AS A_PURCHASE_TRANSACTION_SOURCE

        --METRICS
        ,PURCHASE_LINES.M_AMOUNT
        ,PURCHASE_LINES.M_ACCOUNT_EXPENSE_TAX_AMOUNT        
        ,PURCHASE_LINES.M_ITEM_EXPENSE_UNIT_PRICE
        ,PURCHASE_LINES.M_ITEM_EXPENSE_QUANTITY

         --METADATA
        ,CURRENT_TIMESTAMP as MD_LOAD_DTS
        ,'{{invocation_id}}' AS MD_INTGR_ID
    FROM PURCHASE

    INNER JOIN PURCHASE_LINES 
        ON PURCHASE.K_PURCHASE_DLHK = PURCHASE_LINES.K_PURCHASE_DLHK
    LEFT JOIN ITEMS
        ON ITEMS.K_ITEM_DLHK = PURCHASE_LINES.K_ITEM_EXPENSE_DLHK
)

SELECT *
FROM FINAL