{{ config (
  materialized= 'view',
  schema= 'SNOWFLAKE_USAGE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source(var('account_usage_schema'),'TABLES')}}
),
rename AS 
(   
  SELECT 
  --DLHK
  MD5(S.TABLE_ID) AS K_TABLE_DLHK
  ,MD5(CONCAT(COALESCE(S.TABLE_NAME,'A'),COALESCE(S.TABLE_SCHEMA_ID,0),COALESCE(S.TABLE_CATALOG_ID,0))) AS K_UNIQUE_TABLE_DLHK
  --BUSINESS KEYS
  ,S.TABLE_ID AS K_TABLE_BK
  ,S.TABLE_CATALOG_ID AS K_DATABASE_BK
  ,S.TABLE_SCHEMA_ID AS K_TABLE_SCHEMA_BK
  --ATTRIBUTES  
  ,S.AUTO_CLUSTERING_ON AS A_AUTO_CLUSTERING_ON
  ,S.CLUSTERING_KEY AS A_CLUSTERING_KEY
  ,S.COMMENT AS A_COMMENT
  ,S.COMMIT_ACTION AS A_COMMIT_ACTION   
  ,S.REFERENCE_GENERATION AS A_REFERENCE_GENERATION
  ,S.SELF_REFERENCING_COLUMN_NAME AS A_SELF_REFERENCING_COLUMN_NAME
  ,CONCAT(S.TABLE_CATALOG,'.',TABLE_SCHEMA,'.',TABLE_NAME) AS A_FULLY_QUALIFIED_TABLE_NAME
  ,S.TABLE_CATALOG AS A_TABLE_CATALOG
  ,S.TABLE_NAME AS A_TABLE_NAME
  ,S.TABLE_OWNER AS A_TABLE_OWNER
  ,S.TABLE_SCHEMA AS A_TABLE_SCHEMA
  ,S.TABLE_TYPE AS A_TABLE_TYPE
  ,S.USER_DEFINED_TYPE_CATALOG AS A_USER_DEFINED_TYPE_CATALOG
  ,S.USER_DEFINED_TYPE_NAME AS A_USER_DEFINED_TYPE_NAME
  ,S.USER_DEFINED_TYPE_SCHEMA AS A_USER_DEFINED_TYPE_SCHEMA   
  --BOOLEAN
  ,S.IS_INSERTABLE_INTO='YES' AS B_IS_INSERTABLE_INTO
  ,S.IS_TRANSIENT='YES' AS B_IS_TRANSIENT
  ,S.IS_TYPED='YES' AS B_IS_TYPED
  --METRICS
  ,S.BYTES AS M_BYTES
  ,S.RETENTION_TIME AS M_RETENTION_TIME
  ,S.ROW_COUNT AS M_ROW_COUNT
  ,S.LAST_ALTERED AS A_LAST_ALTERED_AT_DTS
  --//metadata (MD)  
  ,S.DELETED AS MD_VALID_TO_DTS
  ,S.DELETED IS NOT NULL AS MD_IS_DELETED
  ,CURRENT_TIMESTAMP as MD_ELT_UPDATED_DTS
  ,'{{invocation_id}}' AS MD_INTGR_ID

  FROM
    source S
)


SELECT * FROM rename