version: 2



models:  
  - name: W_TABLES_D
    description: This is the tables dimension table
    columns:
      - name: K_TABLE_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the customer           
