{{ config (
  materialized= 'view',
  schema= 'XERO',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('DEMO_XERO','ACCOUNTS')}}
),
rename AS 
(   
SELECT 
    --MD5
    MD5( TRIM(COALESCE(ACCOUNT_ID,'00000000000000000000000000000000')) ) AS K_ACCOUNT_DLHK
    --BUSINESS KEYS
    ,ACCOUNT_ID AS K_ACCOUNT_BK
    --ATTRIBUTES
    ,BANK_ACCOUNT_NUMBER AS A_BANK_ACCOUNT_NUMBER
    ,BANK_ACCOUNT_TYPE AS A_BANK_ACCOUNT_TYPE
    ,CLASS AS A_CLASS
    ,CODE AS A_CODE
    ,CURRENCY_CODE AS A_CURRENCY_CODE
    ,DESCRIPTION AS A_DESCRIPTION
    ,NAME AS A_NAME
    ,REPORTING_CODE AS A_REPORTING_CODE
    ,REPORTING_CODENAME AS A_REPORTING_CODENAME
    ,STATUS AS A_STATUS
    ,SYSTEM_ACCOUNT AS A_SYSTEM_ACCOUNT
    ,TAX_TYPE AS A_TAX_TYPE
    ,TYPE AS A_TYPE
    ,UPDATED_DATE_UTC AS A_UPDATED_AT_DTS
    --BOOLEAN
    ,ADD_TO_WATCHLIST AS B_ADD_TO_WATCHLIST
    ,ENABLE_PAYMENTS_TO_ACCOUNT AS B_ENABLE_PAYMENTS_TO_ACCOUNT
    ,HAS_ATTACHMENTS AS B_HAS_ATTACHMENTS
    ,SHOW_IN_EXPENSE_CLAIMS AS B_SHOW_IN_EXPENSE_CLAIMS
    --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
  FROM
    source  A    
)


SELECT * FROM rename