 config {
  type: "table",
  schema: "DATAFORM_XERO",
  tags: ["staging", "daily"],
  snowflake: { 
     transient: false 
  },  description: "This is the contacts dimension table",
  columns: {
 
    K_CONTACT_DLHK: "DataLakeHouse key of the contact",
  },
  assertions: {
    uniqueKey: ["K_CONTACT_DLHK"],
    nonNull: ["K_CONTACT_DLHK"]

  }, 


}


SELECT
  *
FROM
  ${ref("V_CONTACTS_STG")} AS C