 config {
  type: "table",
  schema: "DATAFORM_XERO",
  tags: ["staging", "daily"],
  snowflake: { 
     transient: false 
  },  description: "This is the invoices fact table",
  columns: {
 
    K_INVOICE_LINE_DLHK: "DataLakeHouse key of the invoices fact",
  },
  assertions: {
    uniqueKey: ["K_INVOICE_LINE_DLHK"],
    nonNull: ["K_INVOICE_LINE_DLHK"]

  }, 


}


SELECT
  *
FROM
  ${ref("V_INVOICES_STG")} AS C