 config {
  type: "view",
  schema: "DATAFORM_DOORDASH",
  tags: ["staging","daily"]

}

WITH source AS (
  SELECT * FROM  ${ref("TEST_SCHEMA_EXT_DEV","DOORDASH_RAW")}
),
rename AS 
(
SELECT DISTINCT 
  MD5(MERCHANT) AS K_MERCHANT_DLHK
  ,MERCHANT AS A_MERCHANT_NAME  
  , (SELECT invocation_id FROM ${ref("H_INVOCATION_ID")}) as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  source
WHERE
 MERCHANT IS NOT NULL
)

SELECT * FROM rename