{{ config (
  materialized= 'view',
  schema= 'QUICKBOOKS',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('DEMO_QUICKBOOKS_SANDBOX','PAYMENT')}}
),
accounts AS (
    SELECT * FROM {{ref('W_ACCOUNTS_D')}}
),
currency AS (
    SELECT * FROM {{ref('W_CURRENCY_D')}}
),

customers AS (
    SELECT * FROM {{ref('W_CUSTOMERS_D')}}
),

rename AS 
(   
SELECT
    --DLHK
    MD5( TRIM(COALESCE(P.ID,'00000000000000000000000000000000')) ) AS K_PAYMENT_DLHK
    ,C.K_CURRENCY_DLHK
    ,CUS.K_CUSTOMER_DLHK
    ,A_DEPOSIT.K_ACCOUNT_DLHK AS K_DEPOSIT_TO_ACCOUNT_DLHK
    ,A_RECEIVABLE.K_ACCOUNT_DLHK AS K_RECEIVABLE_ACCOUNT_DLHK
    --BUSINESS KEYS
    ,P.ID AS K_PAYMENT_BK
    ,P.CREDIT_CARD_CCTRANS_ID AS K_CREDIT_CARD_CCTRANS_BK
    ,P.CURRENCY_ID AS K_CURRENCY_BK
    ,P.CUSTOMER_ID AS K_CUSTOMER_BK
    ,P.DEPOSIT_TO_ACCOUNT_ID AS K_DEPOSIT_TO_ACCOUNT_BK    
    ,P.PAYMENT_METHOD_ID AS K_PAYMENT_METHOD_BK
    ,P.RECEIVABLE_ACCOUNT_ID AS K_RECEIVABLE_ACCOUNT_BK

    --ATTRIBUTES
    ,P.CREATED_AT AS A_CREATED_AT_DTS
    ,P.UPDATED_AT AS A_UPDATED_AT_DTS
    ,P.CREDIT_CARD_AUTH_CODE AS A_CREDIT_CARD_AUTH_CODE
    ,P.CREDIT_CARD_BILLING_ADDRESS_STREET AS A_CREDIT_CARD_BILLING_ADDRESS_STREET
    ,P.CREDIT_CARD_CC_EXPIRY_MONTH AS A_CREDIT_CARD_CC_EXPIRY_MONTH
    ,P.CREDIT_CARD_CC_EXPIRY_YEAR AS A_CREDIT_CARD_CC_EXPIRY_YEAR
    ,P.CREDIT_CARD_NAME_ON_ACCOUNT AS A_CREDIT_CARD_NAME_ON_ACCOUNT
    ,P.CREDIT_CARD_POSTAL_CODE AS A_CREDIT_CARD_POSTAL_CODE
    ,P.CREDIT_CARD_STATUS AS A_CREDIT_CARD_STATUS
    ,P.CREDIT_CARD_TRANSACTION_AUTHORIZATION_TIME AS A_CREDIT_CARD_TRANSACTION_AUTHORIZATION_TIME
    ,P.CREDIT_CARD_TYPE AS A_CREDIT_CARD_TYPE
    ,P.PRIVATE_NOTE AS A_PRIVATE_NOTE
    ,P.REFERENCE_NUMBER AS A_REFERENCE_NUMBER
    ,P.SYNC_TOKEN AS A_SYNC_TOKEN
    ,P.TRANSACTION_DATE AS A_TRANSACTION_DATE
    ,P.TRANSACTION_SOURCE AS A_TRANSACTION_SOURCE
    ,P.TRANSACTION_STATUS AS A_TRANSACTION_STATUS
    --BOOLEAN
    ,P.CREDIT_CARD_PROCESS_PAYMENT AS B_CREDIT_CARD_PROCESS_PAYMENT
    ,P.PROCESS_PAYMENT AS B_PROCESS_PAYMENT
    --METRICS
    ,P.CREDIT_CARD_AMOUNT::DECIMAL(15,2) AS M_CREDIT_CARD_AMOUNT
    ,P.EXCHANGE_RATE::DECIMAL(15,2) AS M_EXCHANGE_RATE
    ,P.TOTAL_AMOUNT::DECIMAL(15,2) AS M_TOTAL_AMOUNT
    ,P.UNAPPLIED_AMOUNT::DECIMAL(15,2) AS M_UNAPPLIED_AMOUNT
    --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID 
  FROM
    source  P
    LEFT JOIN currency C ON C.K_CURRENCY_BK = P.CURRENCY_ID    
    LEFT JOIN customers CUS ON CUS.K_CUSTOMER_BK = P.CUSTOMER_ID    
    LEFT JOIN accounts A_DEPOSIT ON A_DEPOSIT.K_ACCOUNT_BK = P.DEPOSIT_TO_ACCOUNT_ID
    LEFT JOIN accounts A_RECEIVABLE ON A_RECEIVABLE.K_ACCOUNT_BK = P.RECEIVABLE_ACCOUNT_ID
)


SELECT * FROM rename