
{{ config (
  materialized= 'view',
  schema= 'QUICKBOOKS',
  tags= ["staging", "daily"]
)
}}

WITH PAYMENTS AS (
    SELECT *
    FROM {{ref('V_PAYMENT_HEADER_STG')}}
),

PAYMENT_LINES AS (
    SELECT *
    FROM {{ref('V_PAYMENT_LINE_STG')}}
),

FINAL AS (
    SELECT
        --DLHK
        PAYMENT_LINES.K_PAYMENT_LINE_DLHK
        ,PAYMENTS.K_CURRENCY_DLHK
        ,PAYMENTS.K_CUSTOMER_DLHK
        ,PAYMENTS.K_DEPOSIT_TO_ACCOUNT_DLHK
        ,PAYMENTS.K_RECEIVABLE_ACCOUNT_DLHK
        
        --BK
        ,PAYMENTS.K_PAYMENT_BK
        ,PAYMENTS.K_CREDIT_CARD_CCTRANS_BK
        ,PAYMENTS.K_CURRENCY_BK
        ,PAYMENTS.K_CUSTOMER_BK
        ,PAYMENTS.K_DEPOSIT_TO_ACCOUNT_BK    
        ,PAYMENTS.K_PAYMENT_METHOD_BK
        ,PAYMENTS.K_RECEIVABLE_ACCOUNT_BK

        ,PAYMENT_LINES.K_CREDIT_CARD_CHARGE_BK
        ,PAYMENT_LINES.K_CREDIT_CARD_CREDIT_BK
        ,PAYMENT_LINES.K_CREDIT_MEMO_BK
        ,PAYMENT_LINES.K_DEPOSIT_BK
        ,PAYMENT_LINES.K_EXPENSE_BK
        ,PAYMENT_LINES.K_INVOICE_BK
        ,PAYMENT_LINES.K_JOURNAL_ENTRY_BK
        ,PAYMENT_LINES.K_CHECK_BK
        --ATTRIBUTES 
        
        ,PAYMENT_LINES.A_INDEX
        ,PAYMENTS.A_CREATED_AT_DTS
        ,PAYMENTS.A_UPDATED_AT_DTS
        ,PAYMENTS.A_CREDIT_CARD_AUTH_CODE
        ,PAYMENTS.A_CREDIT_CARD_BILLING_ADDRESS_STREET
        ,PAYMENTS.A_CREDIT_CARD_CC_EXPIRY_MONTH
        ,PAYMENTS.A_CREDIT_CARD_CC_EXPIRY_YEAR
        ,PAYMENTS.A_CREDIT_CARD_NAME_ON_ACCOUNT
        ,PAYMENTS.A_CREDIT_CARD_POSTAL_CODE
        ,PAYMENTS.A_CREDIT_CARD_STATUS
        ,PAYMENTS.A_CREDIT_CARD_TRANSACTION_AUTHORIZATION_TIME
        ,PAYMENTS.A_CREDIT_CARD_TYPE
        ,PAYMENTS.A_PRIVATE_NOTE
        ,PAYMENTS.A_REFERENCE_NUMBER
        ,PAYMENTS.A_SYNC_TOKEN
        ,PAYMENTS.A_TRANSACTION_DATE
        ,PAYMENTS.A_TRANSACTION_SOURCE
        ,PAYMENTS.A_TRANSACTION_STATUS
        --BOOLEAN
        ,PAYMENTS.B_CREDIT_CARD_PROCESS_PAYMENT
        ,PAYMENTS.B_PROCESS_PAYMENT
        --METRICS
        ,PAYMENT_LINES.M_AMOUNT      
         --METADATA
        ,CURRENT_TIMESTAMP as MD_LOAD_DTS
        ,'{{invocation_id}}' AS MD_INTGR_ID
    FROM PAYMENTS

    INNER JOIN PAYMENT_LINES 
        ON PAYMENTS.K_PAYMENT_DLHK = PAYMENT_LINES.K_PAYMENT_DLHK
    
)

SELECT *
FROM FINAL