 config {
  type: "table",
  schema: "DATAFORM_SALESFORCE",
  tags: ["staging", "daily"],
  snowflake: { 
     transient: false 
  },  description: "This is the accounts dimension table",
  columns: {
 
    K_ACCOUNT_DLHK: "DataLakeHouse key of the account",
  },
  assertions: {
    uniqueKey: ["K_ACCOUNT_DLHK"],
    nonNull: ["K_ACCOUNT_DLHK"]

  }, 


}

SELECT
  *
FROM
  ${ref("V_ACCOUNTS_STG")} AS C