 config {
  type: "table",
  schema: "DATAFORM_SALESFORCE",
  tags: ["staging", "daily"],
  snowflake: { 
     transient: false 
  },  description: "This is the campaigns fact table",
  columns: {
 
    K_CAMPAIGN_DLHK: "DataLakeHouse key of the campaign",
  },
  assertions: {
    uniqueKey: ["K_CAMPAIGN_DLHK"],
    nonNull: ["K_CAMPAIGN_DLHK"]

  }, 


}

SELECT
  *
FROM
  ${ref("V_CAMPAIGNS_STG")} AS C