 config {
  type: "table",
  schema: "DATAFORM_SALESFORCE",
  tags: ["staging", "daily"],
  snowflake: { 
     transient: false 
  },  description: "This is the contracts dimension table",
  columns: {
 
    K_CONTRACT_DLHK: "DataLakeHouse key of the contract",
  },
  assertions: {
    uniqueKey: ["K_CONTRACT_DLHK"],
    nonNull: ["K_CONTRACT_DLHK"]

  }, 


}

SELECT
  *
FROM
  ${ref("V_CONTRACTS_STG")} AS C