{{ config (
  materialized= 'table',
  schema= 'SQUARE',
  tags= ["staging", "daily"],
  transient=false
)
}}


SELECT
  --MD5 KEYS
  K_POS_CATALOG_OBJECT_HASH_DLHK
  ,K_POS_CATALOG_OBJECT_VARIATION_DLHK AS K_POS_CATALOG_OBJECT_DLHK
  ,K_POS_CATALOG_OBJECT_DLHK AS K_POS_CATALOG_OBJECT_ITEM_DLHK
  --BUSINESS KEYS
  ,K_POS_CATALOG_OBJECT_VARIATION_BK AS K_POS_CATALOG_OBJECT_BK
  ,K_POS_LOCATION_BK
  ,K_POS_CATALOG_OBJECT_BK AS K_POS_CATALOG_OBJECT_ITEM_BK
  --ATTRIBUTUES
  
  ,A_POS_PRODUCT_SUB_NAME AS A_POS_CATALOG_OBJECT_NAME
  ,A_POS_PRODUCT_NAME
 
  ,A_POS_CATEGORY_NAME
  ,A_POS_USAGE
  ,A_POS_VARIATION_PRICE_MONEY_CURRENCY AS A_POS_PRICE_MONEY_CURRENY
  --,A_POS_VARIATION_PRICING_TYPE AS A_POS_PRICING_TYPE
  --METRICS
  ,M_POS_PRICE_MONEY_AMOUNT
  --METADATA
  ,MD_LOAD_DTS
  ,MD_INTGR_ID
FROM
  {{ref('V_CATALOG_ITEM_VARIATION_STG')}} AS CIV

UNION ALL

SELECT
    --MD5 KEYS
    K_POS_CATALOG_OBJECT_HASH_DLHK
    ,K_POS_CATALOG_MODIFIER_DLHK
    ,K_POS_CATALOG_OBJECT_DLHK
    --BUSINESS KEYS
    ,K_POS_CATALOG_MODIFIER_BK
    ,K_POS_LOCATION_BK
    ,K_POS_CATALOG_OBJECT_BK
     --ATTRIBUTES  
    ,A_POS_CATALOG_MODIFIER_NAME
    ,A_POS_PRODUCT_NAME

    ,A_POS_CATEGORY_NAME
    ,A_POS_USAGE
    ,A_POS_PRICE_MONEY_CURRENCY
    --,NULL AS A_POS_PRICING_TYPE
    --METRICS
    ,M_PRICE_MONEY_AMOUNT
    --METADATA (MD)
    ,MD_LOAD_DTS
    ,MD_INTGR_ID
FROM
  {{ref('V_CATALOG_ITEM_MODIFIER_STG')}} AS CIM





  