{{ config (
  materialized= 'view',
  schema= 'XERO',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('DEMO_XERO','PAYMENT')}}
),
account AS (
  SELECT 
  * 
  FROM  	
    {{ref('W_ACCOUNTS_D')}}
),
rename AS (
SELECT
    --DLHK
    MD5( TRIM(COALESCE(S.PAYMENT_ID,'00000000000000000000000000000000')) ) AS K_PAYMENT_DLHK
    ,A.K_ACCOUNT_DLHK
    --BUSINESS KEYS
    ,S.PAYMENT_ID AS K_PAYMENT_BK
    ,S.PREPAYMENT_ID AS K_PREPAYMENT_BK
    ,S.BATCH_PAYMENT_ID AS K_BATCH_PAYMENT_BK
    ,S.ACCOUNT_ID AS K_ACCOUNT_BK    
    ,S.CREDIT_NOTE_ID AS K_CREDIT_NOTE_BK
    ,S.EXPENSE_CLAIM_ID AS K_EXPENSE_CLAIM_BK    
    ,S.INVOICE_ID AS K_INVOICE_BK
    ,S.OVERPAYMENT_ID AS K_OVERPAYMENT_BK
    --ATTRIBUTES
    ,S.BATCH_PAYMENT_DATE AS A_BATCH_PAYMENT_DATE
    ,S.BATCH_PAYMENT_STATUS AS A_BATCH_PAYMENT_STATUS
    ,S.BATCH_PAYMENT_TYPE AS A_BATCH_PAYMENT_TYPE
    ,S.BATCH_PAYMENT_UPDATED_DATE_UTC AS A_BATCH_PAYMENT_UPDATED_DATE_DTS
    ,S.PAYMENT_TYPE AS A_PAYMENT_TYPE
    ,S.PAY_DATE AS A_PAY_DATE
    ,S.REFERENCE AS A_REFERENCE
    ,S.STATUS AS A_STATUS
    ,S.UPDATED_DATE_UTC AS A_UPDATED_DATE_DTS
    ,S.BATCH_PAYMENT_IS_RECONCILED AS B_BATCH_PAYMENT_IS_RECONCILED    
    --BOOLEAN
    ,S.HAS_ACCOUNT::BOOLEAN AS B_HAS_ACCOUNT
    ,S.IS_RECONCILED::BOOLEAN AS B_IS_RECONCILED
    ,S.HAS_VALIDATION_ERRORS::BOOLEAN AS B_HAS_VALIDATION_ERRORS
    --METRICS    
    ,S.AMOUNT::DECIMAL(15,2) AS M_AMOUNT
    ,S.BANK_AMOUNT::DECIMAL(15,2) AS M_BANK_AMOUNT
    ,S.BATCH_PAYMENT_TOTAL_AMOUNT::DECIMAL(15,2) AS M_BATCH_PAYMENT_TOTAL_AMOUNT
    ,S.CURRENCY_RATE::DECIMAL(15,2) AS M_CURRENCY_RATE
        --METADATA (MD)
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
FROM 
    source S
    LEFT JOIN account A on A.K_ACCOUNT_BK = S.ACCOUNT_ID
)

SELECT * FROM rename