{{ config (
  materialized= 'view',
  schema= 'XERO',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('DEMO_XERO','RECEIPT_LINE_ITEM')}}
),
contact AS (
  SELECT 
  * 
  FROM  	
    {{ref('W_CONTACTS_D')}}
),
account AS (
  SELECT 
  * 
  FROM  	
    {{ref('W_ACCOUNTS_D')}}
),
item AS (
  SELECT 
  * 
  FROM  	
     {{ref('W_ITEMS_D')}}
),
rename AS (
SELECT
    --DLHK
    MD5( TRIM(COALESCE(CONCAT(S.RECEIPT_ID,'-',CAST(S.RECEIPT_LINE AS VARCHAR)),'00000000000000000000000000000000')) ) AS K_RECEIPT_LINE_DLHK
    ,MD5( TRIM(COALESCE(S.RECEIPT_ID,'00000000000000000000000000000000')) ) AS K_RECEIPT_DLHK
    ,A.K_ACCOUNT_DLHK
    ,I.K_ITEM_DLHK
    --BUSINESS KEYS  
    ,A.K_ACCOUNT_BK
    ,I.K_ITEM_BK
    ,S.RECEIPT_ID AS K_RECEIPT_BK
    --ATTRIBUTES
    ,S.RECEIPT_LINE AS A_RECEIPT_LINE
    ,S.ACCOUNT_CODE AS A_ACCOUNT_CODE
    ,S.DESCRIPTION AS A_DESCRIPTION
    ,S.ITEM_CODE AS A_ITEM_CODE
    ,S.TAX_TYPE AS A_TAX_TYPE
    --METRICS
    ,S.DISCOUNT_RATE::DECIMAL(15,2) AS M_DISCOUNT_RATE
    ,S.LINE_AMOUNT::DECIMAL(15,2) AS M_LINE_AMOUNT
    ,S.QUANTITY::DECIMAL(15,2) AS M_QUANTITY
    ,S.TAX_AMOUNT::DECIMAL(15,2) AS M_TAX_AMOUNT
    ,S.UNIT_AMOUNT::DECIMAL(15,2) AS M_UNIT_AMOUNT
FROM 
    source S
    LEFT JOIN account A on A.A_CODE = S.ACCOUNT_CODE
    LEFT JOIN item I ON I.A_CODE = S.ITEM_CODE
)

SELECT * FROM rename