{{ config (
  materialized= 'view',
  schema= 'XERO',
  tags= ["staging","daily"]
)
}}

WITH RECEIPT_HEADER AS (
  SELECT 
  * 
  FROM  	
    {{ref('V_RECEIPT_HEADER_STG')}}
),
RECEIPT_LINE AS (
  SELECT
  *
  FROM
    {{ref('V_RECEIPT_ITEM_STG')}}
),
rename AS 
(  
SELECT
    --DLHK
    RL.K_RECEIPT_LINE_DLHK
    ,S.K_RECEIPT_DLHK
    ,S.K_CONTACT_DLHK
    ,RL.K_ACCOUNT_DLHK
    ,RL.K_ITEM_DLHK
    --BUSINESS KEYS
    ,S.K_RECEIPT_BK
    ,S.K_CONTACT_BK
    ,S.K_EXPENSE_CLAIM_BK
    ,S.K_USER_BK
    ,RL.K_ACCOUNT_BK
    ,RL.K_ITEM_BK
    --ATTRIBUTES
    ,RL.A_RECEIPT_LINE
    ,RL.A_DESCRIPTION AS A_RECEIPT_LINE_DESCRIPTION
    ,RL.A_TAX_TYPE AS A_RECEIPT_LINE_TAX_TYPE
    ,S.A_LINE_AMOUNT_TYPES
    ,S.A_REFERENCE
    ,S.A_RECEIPT_DATE
    ,S.A_STATUS
    ,S.A_UPDATED_DATE_DTS
    ,S.A_URL
    --BOOLEAN
    ,S.B_HAS_ATTACHMENTS
    --METRICS
    ,RL.M_DISCOUNT_RATE
    ,RL.M_LINE_AMOUNT
    ,RL.M_QUANTITY
    ,RL.M_TAX_AMOUNT
    ,RL.M_UNIT_AMOUNT
    --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
FROM
    RECEIPT_HEADER S
    LEFT JOIN RECEIPT_LINE RL on RL.K_RECEIPT_DLHK = S.K_RECEIPT_DLHK    
)

SELECT * FROM rename