version: 2

sources:      
  - name: "{{ var('account_usage_schema')}}"
    database: "{{ var('snowflake_database')}}"
    schema: "{{ var('account_usage_schema')}}"
    quoting:
      identifier: true
    tables:      
      - name: TABLES
      - name: COLUMNS      
      - name: DATABASES
      - name: FILE_FORMATS
      - name: FUNCTIONS                  
      - name: LOAD_HISTORY
      - name: LOGIN_HISTORY
      - name: QUERY_HISTORY
      - name: REFERENCIAL_CONSTRAINTS
      - name: SCHEMADATA
      - name: SEQUENCES
      - name: STAGES
      - name: STORAGE_USAGE      
      - name: TABLE_CONSTRAINTS
      - name: TABLE_STORAGE_METRICS
      - name: VIEWS
      - name: WAREHOUSE_METERING_HISTORY
      - name: ACCESS_HISTORY
      - name: USERS
      - name: DATABASE_STORAGE_USAGE_HISTORY
  - name: "{{ var('organization_usage_schema')}}"
    database: "{{ var('snowflake_database')}}"    
    schema: "{{ var('organization_usage_schema')}}"
    quoting:
      identifier: true
    tables:      
      - name: RATE_SHEET_DAILY