{{ config (
  materialized= 'view',
  schema= 'XERO',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('DEMO_XERO','INVOICE_LINE_ITEM')}}
),
account AS (
  SELECT 
  * 
  FROM  	
    {{ref('W_ACCOUNTS_D')}}
),
item AS (
  SELECT 
  * 
  FROM  	
     {{ref('W_ITEMS_D')}}
),
rename AS 
(  
SELECT
    --DLHK
    MD5( TRIM(COALESCE(S.LINE_ITEM_ID,'00000000000000000000000000000000')) ) AS K_INVOICE_LINE_DLHK
    ,MD5( TRIM(COALESCE(S.INVOICE_ID,'00000000000000000000000000000000')) ) AS K_INVOICE_DLHK
    ,A.K_ACCOUNT_DLHK
    ,I.K_ITEM_DLHK
    --BUSINESS KEYS
    ,S.INVOICE_ID AS K_INVOICE_BK
    ,S.LINE_ITEM_ID AS K_INVOICE_LINE_BK
    --ATTRIBUTES
    ,S.ACCOUNT_CODE AS A_ACCOUNT_CODE
    ,S.DESCRIPTION AS A_DESCRIPTION
    ,S.ITEM_CODE AS A_ITEM_CODE
    ,S.TAX_TYPE AS A_TAX_TYPE
    ,S.VALIDATION_ERRORS AS A_VALIDATION_ERRORS
    --BOOLEAN
    ,S.DISCOUNT_ENTERED_AS_PERCENT AS B_DISCOUNT_ENTERED_AS_PERCENT
    --METRICS    
    ,S.DISCOUNT_RATE::DECIMAL(15,2) AS M_DISCOUNT_RATE
    ,S.LINE_AMOUNT::DECIMAL(15,2) AS M_LINE_AMOUNT
    ,S.QUANTITY::DECIMAL(15,2) AS M_QUANTITY
    ,S.TAX_AMOUNT::DECIMAL(15,2) AS M_TAX_AMOUNT
    ,S.UNIT_AMOUNT::DECIMAL(15,2) AS M_UNIT_AMOUNT
    --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID

FROM
    source S
    LEFT JOIN account A on A.A_CODE = S.ACCOUNT_CODE
    LEFT JOIN item I ON I.A_CODE = S.ITEM_CODE
)

SELECT * FROM rename
