
{{ config (
  materialized= 'view',
  schema= 'QUICKBOOKS',
  tags= ["staging", "daily"]
)
}}

WITH INVOICE AS (
    SELECT *
    FROM {{ref('V_INVOICE_HEADER_STG')}}
),

INVOICE_LINE AS (
    SELECT *
    FROM {{ref('V_INVOICE_LINE_STG')}}
),
INVOICE_LINE_BUNDLE AS (
    SELECT *
    FROM {{ref('V_INVOICE_LINE_BUNDLE_STG')}}
),
FINAL AS (
    SELECT
    --DLHK
    ILB.K_INVOICE_LINE_BUNDLE_DLHK
    ,IL.K_INVOICE_LINE_DLHK
    ,I.K_INVOICE_DLHK
    ,I.K_TERM_DLHK
    ,I.K_CURRENCY_DLHK
    ,I.K_CUSTOMER_DLHK
    ,I.K_DEPOSIT_TO_ACCOUNT_DLHK
    

    ,IL.K_SALES_ITEM_ITEM_DLHK
    ,IL.K_SALES_ITEM_CLASS_DLHK
    ,IL.K_DISCOUNT_ACCOUNT_DLHK
    ,IL.K_SALES_ITEM_ACCOUNT_DLHK
    
    ,ILB.K_ITEM_DLHK AS K_INVOICE_LINE_BUNDLE_ITEM_DLHK
    ,ILB.K_CLASS_DLHK AS K_INVOICE_LINE_BUNDLE_CLASS_DLHK
    ,ILB.K_ACCOUNT_DLHK AS K_INVOICE_LINE_BUNDLE_ACCOUNT_DLHK


    --BK
    ,I.K_INVOICE_BK
    ,I.K_SALES_TERM_BK
    ,I.K_BILLING_ADDRESS_BK
    ,I.K_CURRENCY_BK
    ,I.K_CLASS_BK
    ,I.K_DEPARTMENT_BK
    ,I.K_CUSTOMER_BK
    ,I.K_SHIPPING_ADDRESS_BK
    ,I.K_TAX_CODE_BK
    ,I.K_DEPOSIT_TO_ACCOUNT_BK

    ,IL.K_BUNDLE_BK
    ,IL.K_DESCRIPTION_TAX_CODE_BK
    ,IL.K_DISCOUNT_ACCOUNT_BK
    ,IL.K_DISCOUNT_CLASS_BK
    ,IL.K_DISCOUNT_TAX_CODE_BK    
    ,IL.K_SALES_ITEM_ACCOUNT_BK
    ,IL.K_SALES_ITEM_CLASS_BK
    ,IL.K_SALES_ITEM_ITEM_BK
    ,IL.K_SALES_ITEM_TAX_CODE_BK
    ,IL.K_SUB_TOTAL_ITEM_BK
    --ATTRIBUTES
    ,I.A_DOC_NUMBER
    ,I.A_TRANSACTION_DATE
    ,I.A_BILLING_BCC_EMAIL
    ,I.A_TRANSACTION_SOURCE
    ,I.A_BILLING_EMAIL
    ,I.A_SYNC_TOKEN
    ,I.A_CREATED_AT_DTS
    ,I.A_UPDATED_AT_DTS
    ,I.A_SHIP_DATE
    ,I.A_GLOBAL_TAX_CALCULATION
    ,I.A_DELIVERY_TYPE
    ,I.A_PRINT_STATUS
    ,I.A_DELIVERY_TIME
    ,I.A_BILLING_CC_EMAIL
    ,I.A_CUSTOMER_MEMO
    ,I.A_DUE_DATE
    ,I.A_EMAIL_STATUS
    ,I.A_PRIVATE_NOTE
    ,I.A_TRACKING_NUMBER
    ,I.A_PAYMENT_DATE
    ,I.A_PAYMENT_STATUS
    ,I.A_PAYMENT_AMOUNT

    ,IL.A_DESCRIPTION AS A_INVOICE_LINE_DESCRIPTION
    ,IL.A_DESCRIPTION_SERVICE_DATE
    ,IL.A_DETAIL_TYPE
    ,IL.A_INDEX
    ,IL.A_LINE_NUM
    ,IL.A_SALES_ITEM_SERVICE_DATE
    
    ,ILB.A_DESCRIPTION AS A_INVOICE_LINE_BUNDLE_DESCRIPTION
    ,ILB.A_LINE_NUM AS A_INVOICE_LINE_BUNDLE_LINE_NUM
    ,ILB.A_SERVICE_DATE AS A_INVOICE_LINE_BUNDLE_SERVICE_DATE
    --METRICS
    /*,I.M_DEPOSIT
    ,I.M_TOTAL_AMOUNT
    ,I.M_EXCHANGE_RATE
    ,I.M_TOTAL_TAX
    ,I.M_HOME_TOTAL_AMOUNT
    ,I.M_BALANCE
    ,I.M_HOME_BALANCE*/
    
    ,IL.M_AMOUNT
    ,IL.M_BUNDLE_QUANTITY
    ,IL.M_DISCOUNT_DISCOUNT_PERCENT
    ,IL.M_SALES_ITEM_DISCOUNT_AMOUNT
    ,IL.M_SALES_ITEM_DISCOUNT_RATE
    ,IL.M_SALES_ITEM_QUANTITY
    ,IL.M_SALES_ITEM_UNIT_PRICE

    ,ILB.M_AMOUNT AS M_INVOICE_LINE_BUNDLE_AMOUNT
    ,ILB.M_UNIT_PRICE AS M_INVOICE_LINE_BUNDLE_UNIT_PRICE
    ,ILB.M_QUANTITY AS M_INVOICE_LINE_BUNDLE_QUANTITY
    ,ILB.M_DISCOUNT_AMOUNT AS M_INVOICE_LINE_DISCOUNT_AMOUNT
    ,ILB.M_DISCOUNT_RATE AS M_INVOICE_LINE_BUNDLE_DISCOUNT_RATE
    --BOOLEAN
    ,I.B_ALLOW_IPNPAYMENT
    ,I.B_ALLOW_ONLINE_ACHPAYMENT
    ,I.B_APPLY_TAX_AFTER_DISCOUNT
    ,I.B_ALLOW_ONLINE_CREDIT_CARD_PAYMENT
    ,I.B_ALLOW_ONLINE_PAYMENT

    ,IL.B_DISCOUNT_PERCENT_BASED

    --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
    FROM INVOICE I

    INNER JOIN INVOICE_LINE IL 
        ON I.K_INVOICE_DLHK = IL.K_INVOICE_DLHK
    LEFT JOIN INVOICE_LINE_BUNDLE ILB
        ON IL.K_INVOICE_LINE_DLHK = ILB.K_INVOICE_LINE_DLHK
)

SELECT *
FROM FINAL