version: 2

sources:      
  - name: DEMO_SQUARE_ALT13
    database: DEVELOPER_SANDBOX
    schema: DEMO_SQUARE_ALT13
    quoting:
      identifier: true
    tables:
      - name: CUSTOMER
      - name: ORDER_DISCOUNT
      - name: ORDER_LINE_ITEM
      - name: ORDER
      - name: PAYMENT
      - name: CATALOG_ITEM
      - name: CATALOG_ITEM_VARIATION
      - name: CATALOG_CATEGORY                  
      - name: CATALOG_MODIFIER
      - name: CATALOG_TAX
      - name: CATALOG_DISCOUNT
      - name: ORDER_LINE_ITEM_MODIFIER
      - name: LOCATION
       