{{ config (
  materialized= 'view',
  schema= 'SQUARE',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('DEMO_SQUARE_ALT13','ORDER_LINE_ITEM_MODIFIER')}}
),
source_order AS (
SELECT DISTINCT K_POS_ORDER_DLHK,K_POS_LOCATION_BK  FROM  {{ref('V_ORDER_HEADER_STG')}}
),
source_order_line_item AS (
SELECT DISTINCT A_POS_CATEGORY_NAME,K_POS_ORDER_DLHK,K_POS_CATALOG_OBJECT_DLHK,K_POS_CATALOG_OBJECT_BK, K_POS_ORDER_LINE_BK,A_POS_ORDER_LINE_NAME,A_POS_ORDER_LINE_VARIATION_NAME,K_POS_ORDER_BK FROM  {{ref('V_ORDER_LINE_ITEM_STG')}}
),
source_catalog_modifier AS (
  SELECT * FROM  {{source('DEMO_SQUARE_ALT13','CATALOG_MODIFIER')}}
),

source_catalog_modifier AS (
  SELECT NULL AS ID, NULL AS NAME, NULL AS PRICE_MONEY_AMOUNT, NULL AS PRICE_MONEY_CURRENCY WHERE FALSE
),

rename AS 
(
 SELECT
      --MD5 KEYS
        MD5( UID ) AS K_POS_ORDER_ITEM_MODIFIER_DLHK 
        ,MD5( TRIM(COALESCE(ORDER_ID, '00000000000000000000000000000000'))  ) AS K_POS_ORDER_DLHK
        ,MD5( TRIM(COALESCE(ORDER_LINE_ITEM_ID, '00000000000000000000000000000000'))  ) AS K_POS_ORDER_LINE_ITEM_DLHK
        ,MD5( TRIM(COALESCE(CATALOG_OBJECT_ID, '00000000000000000000000000000000')) ) AS K_POS_CATALOG_OBJECT_DLHK
        ,OLI.K_POS_CATALOG_OBJECT_DLHK AS K_POS_CATALOG_OBJECT_ITEM_DLHK
        ,MD5(CONCAT(MD5(TRIM(COALESCE(CATALOG_OBJECT_ID, '00000000000000000000000000000000'))) ,'-',COALESCE(O.K_POS_LOCATION_BK,'00000000000000000000000000000000'),'-',COALESCE(CM.NAME, S.NAME,'None'),'-',OLI.K_POS_CATALOG_OBJECT_DLHK)) AS K_POS_CATALOG_OBJECT_DLHK_2 
        ,CONCAT(MD5(TRIM(COALESCE(CATALOG_OBJECT_ID, '00000000000000000000000000000000'))) ,'-',COALESCE(O.K_POS_LOCATION_BK,'00000000000000000000000000000000'),'-',COALESCE(CM.NAME, S.NAME,'None'),'-',OLI.K_POS_CATALOG_OBJECT_DLHK) AS K_POS_CATALOG_OBJECT_DLHK_3
     
        ,MD5( TRIM(COALESCE(TOTAL_PRICE_CURRENCY, '00000000000000000000000000000000')) ) AS K_CURRENCY_DLHK 
        --BUSINESS KEYS
        ,UID AS K_POS_ORDER_ITEM_MODIFIER_BK        
        ,ORDER_ID AS K_POS_ORDER_BK
        ,ORDER_LINE_ITEM_ID AS K_POS_ORDER_LINE_ITEM_BK
        ,CATALOG_OBJECT_ID AS K_POS_CATALOG_OBJECT_BK
        ,OLI.K_POS_CATALOG_OBJECT_BK AS K_POS_CATALOG_OBJECT_ITEM_BK
        ,O.K_POS_LOCATION_BK
        
        --ATTRIBUTES
        ,S.NAME AS A_POS_ORDER_LINE_MODIFIER_NAME
        ,COALESCE(CM.NAME, S.NAME) AS A_POS_PRODUCT_NAME
        ,CM.NAME AS A_POS_MODIFIER_NAME
        ,OLI.A_POS_CATEGORY_NAME
        ,CM.PRICE_MONEY_CURRENCY AS A_POS_CATALOG_MODIFIER_PRICE_MONEY_CURRENCY
        
        --METRICS
        ,CM.PRICE_MONEY_AMOUNT AS M_CATALOG_MODIFIER_PRICE_MONEY_AMOUNT 
        ,ROUND(NVL(BASE_PRICE_AMOUNT, 000)/100, 2)::decimal(15,2) AS M_BASE_PRICE_AMT
        ,ROUND(NVL(TOTAL_PRICE_AMOUNT, 000)/100, 2)::decimal(15,2) AS M_TOTAL_PRICE_AMOUNT         
        --METADATA
        , CURRENT_TIMESTAMP AS MD_LOAD_DTS
        , '{{invocation_id}}' AS MD_INTGR_ID
FROM source S
LEFT JOIN source_catalog_modifier AS CM ON CM.ID = S.CATALOG_OBJECT_ID
LEFT JOIN source_order O ON O.K_POS_ORDER_DLHK =MD5( TRIM(COALESCE( S.ORDER_ID, '00000000000000000000000000000000'))  )
LEFT JOIN source_order_line_item as OLI ON  S.ORDER_LINE_ITEM_ID = OLI.K_POS_ORDER_LINE_BK AND S.ORDER_ID = OLI.K_POS_ORDER_BK 
)

SELECT 
 MD5(CONCAT(K_POS_CATALOG_OBJECT_DLHK,K_POS_LOCATION_BK,A_POS_PRODUCT_NAME,COALESCE(A_POS_MODIFIER_NAME,'NA'),K_POS_CATALOG_OBJECT_ITEM_DLHK)) AS K_POS_CATALOG_OBJECT_HASH_DLHK,
*
 FROM rename