 config {
  type: "view",
  schema: "DATAFORM_DOORDASH",
  tags: ["staging","daily"]

}

WITH source AS (
  SELECT * FROM  ${ref("TEST_SCHEMA_EXT_DEV","DOORDASH_RAW")}
),
rename AS 
(
SELECT DISTINCT 
  MD5(CURRENCY) AS K_CURRENCY_DLHK
  ,CURRENCY AS K_CURRENCY_BK
  , (SELECT invocation_id FROM ${ref("H_INVOCATION_ID")}) as MD_INTGR_ID
  , CURRENT_TIMESTAMP() MD_ELT_UPDATED_DTS
FROM 
  source
WHERE
  CURRENCY IS NOT NULL
)

SELECT * FROM rename