version: 2

sources:      
  - name: DEMO_XERO
    database: DEVELOPER_SANDBOX
    schema: DEMO_XERO
    quoting:
      identifier: true
    tables:
      - name: ACCOUNTS
      - name: ALLOCATION
      - name: ASSET
      - name: ASSET_SETTINGS
      - name: ASSET_TYPE
      - name: BRANDING_THEME
      - name: CONTACTS
      - name: CONTACT_ADDRESS
      - name: CONTACT_GROUP                  
      - name: CONTACT_GROUP_MEMBER
      - name: EMPLOYEE
      - name: INVOICE
      - name: INVOICE_LINE_ITEM
      - name: INVOICE_LINE_ITEM_TRACKING_CATEGORY
      - name: ITEM
      - name: JOURNAL
      - name: JOURNAL_LINE
      - name: JOURNAL_LINE_TRACKING_CATEGORY
      - name: MANUAL_JOURNAL_LINE
      - name: MANUAL_JOURNAL
      - name: ORGANISATION
      - name: PAYMENT
      - name: PURCHASE_ORDER
      - name: PURCHASE_ORDER_LINE_ITEM
      - name: RECEIPT
      - name: RECEIPT_LINE_ITEM

  