{{ config (
  materialized= 'view',
  schema= 'XERO',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('DEMO_XERO','CONTACTS')}}
),
contact_group_member AS (
  SELECT
  *
  FROM
    {{source('DEMO_XERO','CONTACT_GROUP_MEMBER')}}
),
contact_group AS (
  SELECT
  *
  FROM
    {{source('DEMO_XERO','CONTACT_GROUP')}}
),
branding_theme AS (
  SELECT
  *
  FROM
    {{ref('V_BRANDING_THEME_STG')}}
),
rename AS 
(  
SELECT
    --DLHK
    MD5( TRIM(COALESCE(S.CONTACT_ID,'00000000000000000000000000000000')) ) AS K_CONTACT_DLHK
    ,B.K_BRANDING_THEME_DLHK
    --BK
    ,S.CONTACT_ID AS K_CONTACT_BK
    ,CG.CONTACT_GROUP_ID AS K_CONTACT_GROUP_BK
    ,S.BRANDING_THEME_ID AS K_BRANDING_THEME_BK    
    --ATTRIBUTES
    ,CG.NAME AS A_CONTACT_GROUP_NAME
    ,CG.STATUS AS A_CONTACT_GROUP_STATUS
    ,B.A_BRANDING_THEME_NAME
    ,S.ACCOUNTS_PAYABLE_TAX_TYPE AS A_ACCOUNTS_PAYABLE_TAX_TYPE
    ,S.ACCOUNTS_RECEIVABLE_TAX_TYPE AS A_ACCOUNTS_RECEIVABLE_TAX_TYPE
    ,S.ACCOUNT_NUMBER AS A_ACCOUNT_NUMBER
    ,S.BANK_ACCOUNT_DETAILS AS A_BANK_ACCOUNT_DETAILS
    ,S.BATCH_PAYMENTS_BANK_ACCOUNT_NAME AS A_BATCH_PAYMENTS_BANK_ACCOUNT_NAME
    ,S.BATCH_PAYMENTS_BANK_ACCOUNT_NUMBER AS A_BATCH_PAYMENTS_BANK_ACCOUNT_NUMBER
    ,S.BATCH_PAYMENTS_CODE AS A_BATCH_PAYMENTS_CODE
    ,S.BATCH_PAYMENTS_DETAILS AS A_BATCH_PAYMENTS_DETAILS
    ,S.BATCH_PAYMENTS_REFERENCE AS A_BATCH_PAYMENTS_REFERENCE
    ,S.CONTACT_NUMBER AS A_CONTACT_NUMBER
    ,S.CONTACT_STATUS AS A_CONTACT_STATUS
    ,S.DEFAULT_CURRENCY AS A_DEFAULT_CURRENCY
    ,S.EMAIL_ADDRESS AS A_EMAIL_ADDRESS
    ,S.FIRST_NAME AS A_FIRST_NAME
    ,S.LAST_NAME AS A_LAST_NAME
    ,{{full_name('FIRST_NAME', 'LAST_NAME')}} AS A_FULL_NAME
    ,S.NAME AS A_NAME
    ,S.PURCHASES_DEFAULT_ACCOUNT_CODE AS A_PURCHASES_DEFAULT_ACCOUNT_CODE
    ,S.SALES_DEFAULT_ACCOUNT_CODE AS A_SALES_DEFAULT_ACCOUNT_CODE
    ,S.SKYPE_USER_NAME AS A_SKYPE_USER_NAME
    ,S.TAX_NUMBER AS A_TAX_NUMBER
    ,S.UPDATED_DATE_UTC AS A_UPDATED_AT_DTS
    ,S.WEBSITE AS A_WEBSITE
    ,S.XERO_NETWORK_KEY AS A_XERO_NETWORK_KEY    
    --BOOLEANS
    ,S.HAS_ATTACHMENTS AS B_HAS_ATTACHMENTS
    ,S.IS_CUSTOMER AS B_IS_CUSTOMER
    ,S.IS_SUPPLIER AS B_IS_SUPPLIER
    ,S.CONTACT_STATUS='ACTIVE' AS B_IS_ACTIVE
    ,S.HAS_VALIDATION_ERRORS::BOOLEAN AS B_HAS_VALIDATION_ERRORS
    --METRICS
    ,S.BALANCES_ACCOUNTS_PAYABLE_OUTSTANDING::DECIMAL(15,2) AS M_BALANCES_ACCOUNTS_PAYABLE_OUTSTANDING
    ,S.BALANCES_ACCOUNTS_PAYABLE_OVERDUE::DECIMAL(15,2) AS M_BALANCES_ACCOUNTS_PAYABLE_OVERDUE
    ,S.BALANCES_ACCOUNTS_RECEIVABLE_OUTSTANDING::DECIMAL(15,2) AS M_BALANCES_ACCOUNTS_RECEIVABLE_OUTSTANDING
    ,S.BALANCES_ACCOUNTS_RECEIVABLE_OVERDUE::DECIMAL(15,2) AS M_BALANCES_ACCOUNTS_RECEIVABLE_OVERDUE
    ,S.DISCOUNT AS M_DISCOUNT
    --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
FROM
    source S
    LEFT JOIN contact_group_member CGM on CGM.CONTACT_ID = S.CONTACT_ID
    LEFT JOIN contact_group CG on CG.CONTACT_GROUP_ID = CGM.CONTACT_GROUP_ID -- CAN I HAVE MORE THAN ONE CONTACT_GROUP PER CONTACT? ON THE CURRENT MODEL WE DON'T HAVE ANY CONTACT GROUPS
    LEFT JOIN branding_theme B ON B.K_BRANDING_THEME_BK = S.BRANDING_THEME_ID
)

SELECT * FROM rename