{{ config (
  materialized= 'table',
  schema= 'SNOWFLAKE_USAGE',
  tags= ["staging", "daily"],
  transient=false
)
}}


SELECT
  C.* 
  ,CASE WHEN RATE.M_EFFECTIVE_RATE IS NULL THEN NULL ELSE C.M_AVERAGE_DATABASE_TERABYTES * RATE.M_EFFECTIVE_RATE END AS M_AMOUNT_BILLABLE_STORAGE
  ,CASE WHEN RATE.M_EFFECTIVE_RATE IS NULL THEN NULL ELSE C.M_AVERAGE_FAILSAFE_TERABYTES * RATE.M_EFFECTIVE_RATE END AS M_AMOUNT_BILLABLE_FAILSAFE
  ,CASE WHEN RATE.M_EFFECTIVE_RATE IS NULL THEN NULL ELSE C.M_BILLABLE_TB * RATE.M_EFFECTIVE_RATE END AS M_AMOUNT_BILLABLE
  ,M_EFFECTIVE_RATE AS M_STORAGE_RATE
  ,A_CURRENCY AS A_RATE_CURRENCY
FROM
  {{ref('V_DATABASE_DAILY_STORAGE_USAGE_STG')}} AS C
  LEFT JOIN {{ref('V_DAILY_RATE_SHEET_STG')}} RATE ON RATE.A_DATE = DATE(C.A_USAGE_DATE) AND RATE.A_USAGE_TYPE = 'storage' AND RATE.K_ACCOUNT_BK = (SELECT CURRENT_ACCOUNT())