{{ config (
  materialized= 'table',
  schema= 'SNOWFLAKE_USAGE',
  tags= ["staging", "daily"],
  transient=false
)
}}


SELECT
  C.* 
  ,CASE WHEN RATE.M_EFFECTIVE_RATE IS NULL THEN NULL ELSE C.M_CREDITS_USED_CLOUD_SERVICES * RATE.M_EFFECTIVE_RATE END AS M_AMOUNT_SPENT_CLOUD_SERVICES
  ,M_EFFECTIVE_RATE AS M_CLOUD_SERVICES_RATE_PER_CREDIT
  ,A_CURRENCY AS A_RATE_CURRENCY
FROM
  {{ref('V_QUERY_HISTORY_STG')}} AS C
  LEFT JOIN {{ref('V_DAILY_RATE_SHEET_STG')}} RATE ON RATE.A_DATE = DATE(C.A_START_TIME) AND RATE.A_USAGE_TYPE = 'cloud services' AND RATE.K_ACCOUNT_BK = (SELECT CURRENT_ACCOUNT())