{{ config (
  materialized= 'view',
  schema= 'XERO',
  tags= ["staging","daily"]
)
}}

WITH PURCHASE_HEADER AS (
  SELECT 
  * 
  FROM  	
    {{ref('V_PURCHASE_ORDER_HEADER_STG')}}
),
PURCHASE_LINE AS (
  SELECT
  *
  FROM
    {{ref('V_PURCHASE_ORDER_LINE_STG')}}
),
rename AS 
(  
SELECT
    --DLHK
    PL.K_PURCHASE_LINE_ITEM_DLHK
    ,S.K_PURCHASE_ORDER_DLHK
    ,S.K_CONTACT_DLHK
    ,S.K_BRANDING_THEME_DLHK
    ,PL.K_ACCOUNT_DLHK
    ,PL.K_ITEM_DLHK
    --BUSINESS KEYS
    ,PL.K_ACCOUNT_BK
    ,PL.K_ITEM_BK
    ,S.K_PURCHASE_ORDER_BK
    ,S.K_BRANDING_THEME_BK
    ,S.K_CONTACT_BK
    --ATTRIBUTES
    ,S.A_ATTENTION_TO
    ,S.A_CURRENCY_CODE
    ,S.A_DELIVERY_ADDRESS
    ,S.A_DELIVERY_DATE
    ,S.A_DELIVERY_INSTRUCTIONS
    ,S.A_LINE_AMOUNT_TYPES
    ,S.A_PO_DATE
    ,S.A_PURCHASE_ORDER_NUMBER
    ,S.A_REFERENCE
    ,S.A_STATUS
    ,S.A_TELEPHONE
    ,S.A_TYPE
    ,S.A_UPDATED_DATE_DTS

    ,PL.A_DESCRIPTION AS A_PURCHASE_LINE_DESCRIPTION
    ,PL.A_TAX_TYPE AS A_PURCHASE_LINE_TAX_TYPE
    --BOOLEAN
    ,S.B_IS_DISCOUNTED
    --METRICS
    ,PL.M_DISCOUNT_RATE
    ,PL.M_GROSS_AMOUNT
    ,PL.M_DISCOUNT_AMOUNT
    ,PL.M_LINE_AMOUNT
    ,PL.M_QUANTITY
    ,PL.M_TAX_AMOUNT
    ,PL.M_UNIT_AMOUNT
    --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
FROM
    PURCHASE_HEADER S
    LEFT JOIN PURCHASE_LINE PL on PL.K_PURCHASE_ORDER_DLHK = S.K_PURCHASE_ORDER_DLHK    
)

SELECT * FROM rename