version: 2



models:  
  - name: W_CUSTOMERS_D
    description: This is the customers dimension table
    columns:
      - name: K_POS_CUSTOMER_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the customer           
  - name: W_CATALOG_ITEM_D
    description: This is the catalog item dimension table
    columns:
      - name: K_POS_CATALOG_OBJECT_HASH_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the item
  - name: W_CURRENCY_D
    description: This is the currency dimension table
    columns:
      - name: K_CURRENCY_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the currency
  - name: W_MERCHANT_LOCATION_D
    description: This is the merchant location dimension table
    columns:
      - name: K_MERCH_LOC_DLHK        
        tests:
          - unique
          - not_null
        description: DataLakeHouse key of the currency
     

