{{ config (
  materialized= 'view',
  schema= 'QUICKBOOKS',
  tags= ["staging", "daily"]
)
}}

WITH source AS (
  SELECT 
  * 
  FROM  	
    {{source('DEMO_QUICKBOOKS','ITEM')}}
),
rename AS 
(   
SELECT 
    --MD5
    MD5( TRIM(COALESCE(A.ID, '00000000000000000000000000000000')) ) AS K_ITEM_DLHK
    ,MD5( TRIM(COALESCE(A.EXPENSE_ACCOUNT_ID, '00000000000000000000000000000000')) ) AS K_EXPENSE_ACCOUNT_DLHK
    --BUSINESS KEYS
    ,A.ID AS K_ITEM_BK
    ,A.ASSET_ACCOUNT_ID AS K_ASSET_ACCOUNT_BK
	,A.INCOME_ACCOUNT_ID  AS K_INCOME_ACCOUNT_BK
	,A.EXPENSE_ACCOUNT_ID AS K_EXPENSE_ACCOUNT_BK
	,A.PARENT_ITEM_ID AS  K_PARENT_ITEM_ACCOUNT_BK
	,A.SALES_TAX_CODE_ID AS K_SALES_TAX_CODE_BK
	,A.PURCHASE_TAX_CODE_ID AS K_PURCHASE_TAX_CODE_BK
    --ATTRIBUTES
    ,A."DESCRIPTION" AS A_ITEM_DESCRIPTION
    ,A.FULLY_QUALIFIED_NAME AS A_FULLY_QUALIFIED_NAME    
    ,regexp_count(A.FULLY_QUALIFIED_NAME, '\\b:\\b', 1) AS A_ITEM_LEVEL
    
    ,NULLIF(SPLIT_PART(A.FULLY_QUALIFIED_NAME,':',1),'') AS A_FIRST_LEVEL_ITEM_NAME
    ,NULLIF(SPLIT_PART(A.FULLY_QUALIFIED_NAME,':',2),'') AS A_SECOND_LEVEL_ITEM_NAME
    ,NULLIF(SPLIT_PART(A.FULLY_QUALIFIED_NAME,':',3),'') AS A_THIRD_LEVEL_ITEM_NAME
    ,NULLIF(SPLIT_PART(A.FULLY_QUALIFIED_NAME,':',4),'') AS A_FOURTH_LEVEL_ITEM_NAME
    ,NULLIF(SPLIT_PART(A.FULLY_QUALIFIED_NAME,':',5),'') AS A_FIFTH_LEVEL_ITEM_NAME
    ,NULLIF(SPLIT_PART(A.FULLY_QUALIFIED_NAME,':',6),'') AS A_SIXTH_LEVEL_ITEM_NAME   
    ,A."NAME" AS A_ITEM_NAME
    ,A.ACTIVE AS A_ACTIVE
    ,A.TYPE AS A_ITEM_TYPE
        
    ,A.LEVEL AS A_LEVEL
    ,A.SUB_ITEM AS A_SUB_ITEM
    ,A.STOCK_KEEPING_UNIT AS A_STOCK_KEEPING_UNIT
    ,A.PURCHASE_DESCRIPTION AS A_PURCHASE_DESCRIPTION
    ,A.INVENTORY_START_DATE::DATE AS A_INVENTORY_START_DATE

    --BOOLEAN
    ,A.SALES_TAX_INCLUDED::BOOLEAN AS B_SALES_TAX_INCLUDED
    ,A.PURCHASE_TAX_INCLUDED::BOOLEAN AS B_PURCHASE_TAX_INCLUDED
    ,A.TRACK_QUANTITY_ON_HAND:BOOLEAN AS B_TRACK_QUANTITY_ON_HAND
    --TIMESTAMP
    ,A.CREATED_AT AS A_CREATED_AT_DTS
    ,A.UPDATED_AT AS A_UPDATED_AT_DTS
    ,A.SYNC_TOKEN AS B_SYNC_TOKEN
    --METRICS
    ,A.QUANTITY_ON_HAND::decimal(15,2) AS M_QUANTITY_ON_HAND
    ,A.UNIT_PRICE::decimal(15,2) AS M_UNITY_PRICE
    ,A.PURCHASE_COST::decimal(15,2) AS M_PURCHASE_COST    
    --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
  FROM
    source  A
    left join source B on B.ID = A.PARENT_ITEM_ID    
)


SELECT * FROM rename