 config {
  type: "table",
  schema: "DATAFORM_QUICKBOOKS",
  tags: ["staging", "daily"],
  snowflake: { 
     transient: false 
  },  description: "This is the employees dimension table",
  columns: {
 
    K_EMPLOYEE_DLHK: "DataLakeHouse key of the employee",
  },
  assertions: {
    uniqueKey: ["K_EMPLOYEE_DLHK"],
    nonNull: ["K_EMPLOYEE_DLHK"]

  }, 


}


SELECT
  *
FROM
  ${ref("V_EMPLOYEES_STG")} AS C