 config {
  type: "table",
  schema: "DATAFORM_QUICKBOOKS",
  tags: ["staging", "daily"],
  snowflake: { 
     transient: false 
  },  description: "This is the vendors dimension table",
  columns: {
 
    K_VENDOR_DLHK: "DataLakeHouse key of the vendor",
  },
  assertions: {
    uniqueKey: ["K_VENDOR_DLHK"],
    nonNull: ["K_VENDOR_DLHK"]

  }, 


}


SELECT
  *
FROM
  ${ref("V_VENDORS_STG")} AS C