{{ config (
  materialized= 'view',
  schema= 'SALESFORCE',
  tags= ["staging","daily"]
)
}}

WITH source AS (
  SELECT * FROM  {{source('DEMO_SALESFORCE','PRODUCT2')}}
),
user AS (
  SELECT * FROM  {{ref('W_USERS_D')}}
),
rename AS 
(
SELECT
    --DLHK
    MD5(S.ID) AS K_PRODUCT_DLHK              
    ,U2.K_USER_DLHK AS K_CREATED_BY_USER_DLHK
    ,U3.K_USER_DLHK AS K_LAST_MODIFIED_BY_USER_DLHK
    --BUSINESS_KEYS
    ,S.ID AS K_PRODUCT_BK
    ,S.CREATEDBYID AS K_CREATED_BY_USER_BK
    ,S.EXTERNALDATASOURCEID AS K_EXTERNAL_DATA_SOURCE_BK
    ,S.EXTERNALID AS K_EXTERNAL_BK
    ,S.LASTMODIFIEDBYID AS K_LAST_MODIFIED_BY_USER_BK
    --ATTRIBUTES
    ,S.CREATEDDATE AS A_CREATED_DATE
    ,S.DESCRIPTION AS A_DESCRIPTION
    ,S.DISPLAYURL AS A_DISPLAY_URL
    ,S.FAMILY AS A_FAMILY
    ,S.LASTMODIFIEDDATE AS A_LAST_MODIFIED_DATE
    ,S.LASTREFERENCEDDATE AS A_LAST_REFERENCED_DATE
    ,S.LASTVIEWEDDATE AS A_LAST_VIEWED_DATE
    ,S.NAME AS A_NAME
    ,S.PRODUCTCODE AS A_PRODUCT_CODE
    ,S.QUANTITYUNITOFMEASURE AS A_QUANTITY_UNIT_OF_MEASURE
    ,S.STOCKKEEPINGUNIT AS A_STOCK_KEEPING_UNIT
    ,S.SYSTEMMODSTAMP AS A_SYSTEM_MOD_STAMP    
    ,S.ISACTIVE AS B_IS_ACTIVE
    ,S.ISARCHIVED AS B_IS_ARCHIVED
    ,S.ISDELETED AS B_IS_DELETED
     --METADATA
    ,CURRENT_TIMESTAMP as MD_LOAD_DTS
    ,'{{invocation_id}}' AS MD_INTGR_ID
FROM
    source S
    LEFT JOIN user U2 ON U2.K_USER_BK = S.CREATEDBYID
    LEFT JOIN user U3 ON U3.K_USER_BK = S.LASTMODIFIEDBYID 
WHERE
    NOT(S.ISDELETED)
)

SELECT * FROM rename